name: Release

on:
  push:
    branches:
      - DPE-1312-adds-release-pipeline
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha
            latest
      - name: Publish Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            TARBALL_PATH=${{ needs.prepare.outputs.tarball-path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
