pegs:
  synapse_conn_id: "SYNAPSE_ORCA_SERVICE_ACCOUNT_CONN"
  aws_conn_id: "AWS_TOWER_PROD_S3_CONN"
  revision: "558a3786e1610a0cb802e384ab082f696030809a" # Updated to the latest revision with new params.entry for PEGS
  challenge_profile: "pegs_challenge_test"
  tower_conn_id: "PEGS_CHALLENGE_PROJECT_TOWER_CONN"
  tower_view_id: "syn58942525"
  tower_compute_env_type: "spot"
  bucket_name: "pegs-challenge-project-tower-scratch"
  key: "10days/pegs_challenge"
  dag_config:
    schedule_interval: "*/1 * * * *"
    start_date: "2024-04-09T00:00:00"  # ISO-format date string; will be converted in the DAG factory
    catchup: false
    default_args:
      retries: 2
    tags:
      - "nextflow_tower"

olfactory-2025:
  synapse_conn_id: "SYNAPSE_ORCA_SERVICE_ACCOUNT_CONN"
  aws_conn_id: "AWS_TOWER_PROD_S3_CONN"
  revision: "652436f5f68a90341150df9c928f390b2469cde1"
  challenge_profile: "olfactory25_challenge_validate"
  tower_conn_id: "OLFACTORY_CHALLENGE_PROJECT_TOWER_CONN"
  tower_view_id: "syn66279193"
  tower_compute_env_type: "spot"
  bucket_name: "TODO"
  key: "10days/olfactory_challenge"
  dag_config:
    schedule_interval: "*/1 * * * *"
    start_date: "2024-04-09T00:00:00"
    catchup: false
    default_args:
      retries: 2
    tags:
      - "nextflow_tower"
